name: cowsay

on:
  push:
  workflow_dispatch:

jobs:
  build-first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install cowsay program
      run: sudo apt-get install cowsay -y

    - name: Execute cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a dragon .... RAWR" > dragon.txt

    - name: Upload dragon.txt as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dragon-artifact
        path: dragon.txt

    - name: read readme file
      run: ls -l
